//! Config file renderers for automatic update backends.
//!
//! Each function takes an [`UpdateSpec`](crate::spec::UpdateSpec) and returns
//! the rendered configuration file content as a `String`. The caller is
//! responsible for writing the content to disk.
//!
//! - [`render_auto_upgrades_conf`] -- `/etc/apt/apt.conf.d/50unattended-upgrades`
//! - [`render_dnf_automatic_conf`] -- `/etc/dnf/automatic.conf`
//! - [`render_apt_conf`] -- `/etc/apt/apt.conf.d/20auto-upgrades`

use crate::spec::{RebootPolicy, Schedule, UpdateSpec};

// ---------------------------------------------------------------------------
// render_auto_upgrades_conf
// ---------------------------------------------------------------------------

/// Render the content of `50unattended-upgrades` for Debian/Ubuntu.
///
/// Generates an APT config snippet that configures `unattended-upgrades`
/// according to the given spec: allowed origins, reboot policy, and
/// email/notification settings.
pub fn render_auto_upgrades_conf(spec: &UpdateSpec) -> String {
    let mut out = String::new();

    out.push_str("// Generated by toride-updates -- do not edit manually\n");
    out.push_str("Unattended-Upgrade {\n");

    // Allowed origins.
    out.push_str("\tAllowed-Origins {\n");
    for origin in &spec.origins {
        out.push_str(&format!("\t\t\"{origin}\";\n"));
    }
    if spec.origins.is_empty() && spec.security_only {
        // Default security-only origins.
        out.push_str("\t\t\"origin=Debian,codename=${distro_codename},label=Debian-Security\";\n");
        out.push_str("\t\t\"origin=Debian,codename=${distro_codename}-security,label=Debian-Security\";\n");
    }
    out.push_str("\t};\n");

    // Auto-fix interrupted dpkg.
    out.push_str("\tAutoFixInterruptedDpkg \"true\";\n");

    // Reboot configuration.
    match spec.reboot {
        RebootPolicy::Never => {
            out.push_str("\tAutomatic-Reboot \"false\";\n");
        }
        RebootPolicy::WhenNeeded => {
            out.push_str("\tAutomatic-Reboot \"true\";\n");
            out.push_str("\tAutomatic-Reboot-WithUsers \"true\";\n");
        }
        RebootPolicy::Always => {
            out.push_str("\tAutomatic-Reboot \"always\";\n");
            out.push_str("\tAutomatic-Reboot-Time \"04:00\";\n");
        }
    }

    // Remove unused dependencies.
    out.push_str("\tRemove-Unused-Dependencies \"true\";\n");

    // Logging.
    out.push_str("\tSyslogEnable \"true\";\n");

    out.push_str("};\n");
    out
}

// ---------------------------------------------------------------------------
// render_dnf_automatic_conf
// ---------------------------------------------------------------------------

/// Render the content of `/etc/dnf/automatic.conf` for Fedora/RHEL.
///
/// Generates an INI-style config for `dnf-automatic` covering update
/// application, reboot, and emitter settings.
pub fn render_dnf_automatic_conf(spec: &UpdateSpec) -> String {
    let mut out = String::new();

    out.push_str("# Generated by toride-updates -- do not edit manually\n\n");

    // [commands] section.
    out.push_str("[commands]\n");
    out.push_str(&format!(
        "apply_updates = {}\n",
        if spec.auto_update { "yes" } else { "no" }
    ));
    match spec.reboot {
        RebootPolicy::Never => {
            out.push_str("reboot = never\n");
        }
        RebootPolicy::WhenNeeded => {
            out.push_str("reboot = when-needed\n");
        }
        RebootPolicy::Always => {
            out.push_str("reboot = always\n");
        }
    }
    out.push('\n');

    // [emitters] section.
    out.push_str("[emitters]\n");
    out.push_str("emit_via = stdio\n");
    out.push_str("system_name = toride-vps\n");
    out.push('\n');

    // [email] section (empty -- no email by default).
    out.push_str("[email]\n");
    out.push_str("# Email notifications are disabled by default.\n");
    out.push('\n');

    // [command] section.
    out.push_str("[command]\n");
    out.push_str("# Custom command hook (unused).\n");
    out.push('\n');

    // [command_email] section.
    out.push_str("[command_email]\n");
    out.push_str("# Command email emitter (unused).\n");
    out.push('\n');

    // [base] section.
    out.push_str("[base]\n");
    out.push_str("debuglevel = 1\n");
    out.push_str(&format!(
        "upgrade_type = {}\n",
        if spec.security_only {
            "security"
        } else {
            "default"
        }
    ));

    out
}

// ---------------------------------------------------------------------------
// render_apt_conf
// ---------------------------------------------------------------------------

/// Render the content of `/etc/apt/apt.conf.d/20auto-upgrades`.
///
/// This small config file simply enables or disables the automatic update
/// machinery:
///
/// ```text
/// APT::Periodic::Update-Package-Lists "1";
/// APT::Periodic::Unattended-Upgrade "1";
/// ```
pub fn render_apt_conf(spec: &UpdateSpec) -> String {
    let enabled = if spec.auto_update { "1" } else { "0" };
    let schedule_val = match &spec.schedule {
        Schedule::Daily => "1",
        Schedule::Weekly => "7",
        Schedule::Monthly => "30",
        Schedule::Custom(_) => "1", // Custom handled via systemd timer.
    };

    format!(
        "// Generated by toride-updates -- do not edit manually\n\
         APT::Periodic::Update-Package-Lists \"{schedule_val}\";\n\
         APT::Periodic::Unattended-Upgrade \"{enabled}\";\n\
         APT::Periodic::Download-Upgradeable-Packages \"{enabled}\";\n\
         APT::Periodic::AutocleanInterval \"7\";\n"
    )
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    fn test_spec() -> UpdateSpec {
        UpdateSpec {
            auto_update: true,
            security_only: true,
            schedule: Schedule::Daily,
            reboot: RebootPolicy::WhenNeeded,
            origins: vec![
                "origin=Debian,codename=${distro_codename},label=Debian-Security".into(),
            ],
        }
    }

    #[test]
    fn render_apt_conf_enabled() {
        let spec = test_spec();
        let conf = render_apt_conf(&spec);
        assert!(conf.contains("\"1\";"));
        assert!(conf.contains("Unattended-Upgrade"));
    }

    #[test]
    fn render_apt_conf_disabled() {
        let spec = UpdateSpec::disabled();
        let conf = render_apt_conf(&spec);
        assert!(conf.contains("\"0\";"));
    }

    #[test]
    fn render_auto_upgrades_conf_contains_origins() {
        let spec = test_spec();
        let conf = render_auto_upgrades_conf(&spec);
        assert!(conf.contains("Allowed-Origins"));
        assert!(conf.contains("Debian-Security"));
    }

    #[test]
    fn render_dnf_automatic_conf_security_only() {
        let spec = test_spec();
        let conf = render_dnf_automatic_conf(&spec);
        assert!(conf.contains("upgrade_type = security"));
        assert!(conf.contains("apply_updates = yes"));
    }
}
