//! Diagnostic and status reports for WireGuard.
//!
//! [`WireguardReport`] provides a snapshot of the WireGuard subsystem status,
//! including active interfaces, peer counts, and health findings.

use std::path::PathBuf;

// ---------------------------------------------------------------------------
// WireguardReport
// ---------------------------------------------------------------------------

/// A comprehensive report of the WireGuard subsystem status.
///
/// Generated by the `doctor` module and used to surface health information
/// to the user.
#[derive(Debug, Clone)]
pub struct WireguardReport {
    /// Whether the `wg` binary was found on the system.
    pub wg_binary_found: bool,
    /// Whether the `wg-quick` binary was found on the system.
    pub wg_quick_binary_found: bool,
    /// Path to the WireGuard config directory.
    pub config_dir: PathBuf,
    /// Whether the config directory exists.
    pub config_dir_exists: bool,
    /// List of active interface reports.
    pub interfaces: Vec<InterfaceReport>,
    /// Health findings from diagnostic checks.
    pub findings: Vec<Finding>,
}

impl Default for WireguardReport {
    fn default() -> Self {
        Self {
            wg_binary_found: false,
            wg_quick_binary_found: false,
            config_dir: PathBuf::from("/etc/wireguard"),
            config_dir_exists: false,
            interfaces: Vec::new(),
            findings: Vec::new(),
        }
    }
}

impl WireguardReport {
    /// Create a new empty report.
    pub fn new() -> Self {
        Self::default()
    }

    /// Returns `true` if there are any error-level findings.
    pub fn has_errors(&self) -> bool {
        self.findings.iter().any(|f| f.severity == Severity::Error)
    }

    /// Returns `true` if there are any warning-level findings.
    pub fn has_warnings(&self) -> bool {
        self.findings.iter().any(|f| f.severity == Severity::Warning)
    }
}

// ---------------------------------------------------------------------------
// InterfaceReport
// ---------------------------------------------------------------------------

/// Status report for a single WireGuard interface.
#[derive(Debug, Clone)]
pub struct InterfaceReport {
    /// Interface name (e.g. `wg0`).
    pub name: String,
    /// Whether the interface is up.
    pub is_up: bool,
    /// Number of configured peers.
    pub peer_count: usize,
    /// Number of peers with established handshakes.
    pub active_peers: usize,
    /// Listen port (0 = auto).
    pub listen_port: u16,
    /// Transfer stats.
    pub stats: TransferStats,
}

/// Transfer statistics for an interface.
#[derive(Debug, Clone, Default)]
pub struct TransferStats {
    /// Total bytes received.
    pub received: u64,
    /// Total bytes sent.
    pub sent: u64,
}

// ---------------------------------------------------------------------------
// Finding
// ---------------------------------------------------------------------------

/// A diagnostic finding from a WireGuard health check.
#[derive(Debug, Clone)]
pub struct Finding {
    /// Unique identifier for the check that produced this finding.
    pub check_id: &'static str,
    /// Severity level.
    pub severity: Severity,
    /// Human-readable description.
    pub message: String,
    /// Suggested fix, if applicable.
    pub fix: Option<String>,
}

impl Finding {
    /// Create a new finding.
    pub fn new(check_id: &'static str, severity: Severity, message: String) -> Self {
        Self {
            check_id,
            severity,
            message,
            fix: None,
        }
    }

    /// Add a suggested fix to this finding.
    pub fn with_fix(mut self, fix: String) -> Self {
        self.fix = Some(fix);
        self
    }
}

// ---------------------------------------------------------------------------
// Severity
// ---------------------------------------------------------------------------

/// Severity level for a diagnostic finding.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum Severity {
    /// Informational -- no action required.
    Info,
    /// Warning -- should be reviewed.
    Warning,
    /// Error -- requires attention.
    Error,
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn default_report() {
        let report = WireguardReport::default();
        assert!(!report.wg_binary_found);
        assert!(report.interfaces.is_empty());
        assert!(report.findings.is_empty());
    }

    #[test]
    fn report_has_errors() {
        let mut report = WireguardReport::default();
        assert!(!report.has_errors());
        report.findings.push(Finding::new(
            "test",
            Severity::Warning,
            "a warning".to_owned(),
        ));
        assert!(!report.has_errors());
        report.findings.push(Finding::new(
            "test",
            Severity::Error,
            "an error".to_owned(),
        ));
        assert!(report.has_errors());
    }

    #[test]
    fn finding_with_fix() {
        let finding = Finding::new("test.check", Severity::Error, "something broke".to_owned())
            .with_fix("do the thing".to_owned());
        assert_eq!(finding.fix.as_deref(), Some("do the thing"));
    }

    #[test]
    fn severity_ordering() {
        assert!(Severity::Info < Severity::Warning);
        assert!(Severity::Warning < Severity::Error);
    }
}
